### ISSUE TITLE
Version history

### ISSUE THREAD

**Issue by tomasko126** [CatBlock/catblock#8]
@kpeckett In my opinion it would be better to change our version history.

Version 1.0 - Imported CatBlock to the repo
Version 1.1 (actually 2.8) - Included all changes needed for 2.8 release
Version 1.2 (actually 3.0) - Included changes for 3.0
..
..
..

What do you think? I think it does make sense, because it can be confusing that AdBlock is at 2.13.x now and we would release 2.8 and so on. Do you agree with this change?

**Comment by itskdog** [comment]
Why do you think this is better? As we are picking up where Michael left off, we should continue with the same number scheme, similar to when LibreOffice branched off of the OpenOffice.org project, starting at version 3.4 instead of restarting from 1.0.

Is there anything I'm not seeing clearly? Please let me know if you've got any further reasons.

**Comment by itskdog** [comment]
After discussion on IRC, we have decided to go with this, as it makes more sense for AdBlock's team, so that they don't see lots of people suddenly using AdBlock 2.8, as it uses the version number from the manifest to send to the ping server.

**Comment by tomasko126** [comment]
@kpeckett We won't ping getadblock's server, because CatBlock by AdBlock team is now unsupported. I've also removed stats file, which actually makes pings to getadblock's stats server. In near future we should consider logging of users on our own.
